import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  Show,
  UserButton,
} from "@clerk/nextjs";
import { Providers } from "./providers";
import { ThemeToggle } from "./ThemeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__varia..."
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <ClerkProvider>
            <header className="border-b">
              <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
                <span className="text-sm font-semibold tracking-tight">Lifting Diary</span>
                <div className="flex items-center gap-2">
                  <Show when="signed-out">
                    <SignInButton mode="modal" />
                    <SignUpButton mode="modal" />
                  </Show>
                  <Show when="signed-in">
                    <UserButton />
                  </Show>
                  <ThemeToggle />
                </div>
              </div>
            </header>
            {children}
          </ClerkProvider>
        </Providers>
      </body>
    </html>
  );
}
